### ISSUE TITLE
Files are already out of date

### ISSUE THREAD

**Issue by harrisonduong** [austinlparker/microcalc#5]
Hi, 

Any chance you would be able to update these files to the latest openTelemetry APIs? I noticed WebTracer class was removed and instead the new one is WebTracerProvider is in the source. I'm a bit of a novice and trying to follow along with the book so any help would be appreciated. 

Thanks.

**Comment by AkatQuas** [comment]
Every thing should go well if you go with `npm ci` to install packages using `package-lock.json`.

**Comment by xzho2604** [comment]
it would have this error even run with **npn ci**

```
web-example@0.0.1 start
> webpack-dev-server -d --progress --colors --port 8090 --config webpack.config.js --hot --inline --host 0.0.0.0 --content-base client

10% building 1/1 modules 0 activeℹ ｢wds｣: Project is running at http://0.0.0.0:8090/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /Users/erikzhou/Desktop/distributed_trace_lab/microcalc/web/client
10% building 1/3 modules 2 active ...p/distributed_trace_lab/microcalc/web/node_modules/webpack/hot/dev-server.jsnode:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/Users/erikzhou/Desktop/distributed_trace_lab/microcalc/web/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/erikzhou/Desktop/distributed_trace_lab/microcalc/web/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/erikzhou/Desktop/distributed_trace_lab/microcalc/web/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/erikzhou/Desktop/distributed_trace_lab/microcalc/web/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/erikzhou/Desktop/distributed_trace_lab/microcalc/web/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/erikzhou/Desktop/distributed_trace_lab/microcalc/web/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/erikzhou/Desktop/distributed_trace_lab/microcalc/web/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/Users/erikzhou/Desktop/distributed_trace_lab/microcalc/web/node_modules/loader-runner/lib/LoaderRunner.js:205:4) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```
